version: 2.1

anchors:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

orbs:
  aws-s3: circleci/aws-s3@2.0.0
  aws-cli: circleci/aws-cli@1.4.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - *attach_workspace
      - checkout
      - run: |
          git submodule sync
          git submodule update --init
      - run:
          name: Install Zola
          command: |
            set -e
            curl -s -L https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
            echo "1a919e00cce61e30c31cd8d0979349ecd3f7c1666d32fa77314cbfbb89447adb  zola.tar.gz" | sha256sum -c
            sudo tar xvzf zola.tar.gz -C /usr/local/bin
            rm zola.tar.gz
      - run:
          name: Build static website
          command: |
            mkdir -p /tmp/{workspace,drafts}
            zola build -o /tmp/workspace/public
            zola build --drafts -o /tmp/workspace/drafts
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - public
            - drafts

  publish:
    docker:
      - image: 'circleci/python:buster'
    steps:
      - *attach_workspace
      - aws-s3/sync:
          from: /tmp/workspace/public/
          to: s3://mkroman-blog
          arguments: |
            --acl public-read
      - aws-cli/setup
      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

  publish-drafts:
    docker:
      - image: 'circleci/python:buster'
    steps:
      - *attach_workspace
      - aws-s3/sync:
          from: /tmp/workspace/drafts/
          to: s3://mkroman-blog-draft
          arguments: |
            --acl public-read
      - aws-cli/setup
      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_DRAFTS --paths "/*"

workflows:
  version: 2

  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - circle-ci
      - publish:
          filters:
            branches:
              only:
                - main
                - circle-ci
          requires:
            - build
      - publish-drafts:
          filters:
            branches:
              only:
                - main
                - circle-ci
          requires:
            - build
