version: 2.1

anchors:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

orbs:
  aws-s3: circleci/aws-s3@1.0.15
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - *attach_workspace
      - checkout
      - run: |
          git submodule sync
          git submodule update --init
      - run:
          name: Install Zola
          command: |
            set -e
            curl -s -L https://github.com/getzola/zola/releases/download/v0.11.0/zola-v0.11.0-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
            echo "8afe40edff5e995afdc132e02442d24eb633ef4b6e81913d69cf97f17905b9c3  zola.tar.gz" | sha256sum -c
            sudo tar xvzf zola.tar.gz -C /usr/local/bin
            rm zola.tar.gz
      - run:
          name: Build static website
          command: |
            mkdir -p /tmp/workspace
            zola build -o /tmp/workspace/public
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - public

  publish:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - *attach_workspace
      - aws-s3/sync:
          from: /tmp/workspace/public/
          to: s3://mkroman-blog
          arguments: |
            --acl public-read
          overwrite: true
      - aws-cli/setup
      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2

  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - circle-ci
      - publish:
          filters:
            branches:
              only:
                - main
                - circle-ci
          requires:
            - build
