version: 2.1

anchors:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

orbs:
  aws-s3: circleci/aws-s3@2.0.0
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - *attach_workspace
      - checkout
      - run: |
          git submodule sync
          git submodule update --init
      - run:
          name: Install Zola
          command: |
            set -e
            curl -s -L https://github.com/getzola/zola/releases/download/v0.12.2/zola-v0.12.2-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
            echo "572e34c4c2b874f9704fb8512abea84532623f7567996bac456291a21c1b2595  zola.tar.gz" | sha256sum -c
            sudo tar xvzf zola.tar.gz -C /usr/local/bin
            rm zola.tar.gz
      - run:
          name: Build static website
          command: |
            mkdir -p /tmp/workspace
            zola build -o /tmp/workspace/public
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - public

  publish:
    docker:
      - image: 'circleci/python:buster'
    steps:
      - *attach_workspace
      - aws-s3/sync:
          from: /tmp/workspace/public/
          to: s3://mkroman-blog
          arguments: |
            --acl public-read
      - aws-cli/setup
      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2

  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - circle-ci
      - publish:
          filters:
            branches:
              only:
                - main
                - circle-ci
          requires:
            - build
