version: 2.1

anchors:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

orbs:
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - *attach_workspace
      - checkout
      - run: |
          git submodule sync
          git submodule update --init
      - run:
          name: Install Zola
          command: |
            curl -s -L https://github.com/getzola/zola/releases/download/v0.10.0/zola-v0.10.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
      - run:
          name: Build static website
          command: |
            mkdir -p /tmp/workspace
            zola build -o /tmp/workspace/public
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - public

  publish:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - *attach_workspace
      - aws-s3/sync:
          from: /tmp/workspace/public/
          to: s3://mkroman-blog
          arguments: |
            --acl public-read
          overwrite: true
      - aws-cli/setup
      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2

  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - circle-ci
      - publish:
          filters:
            branches:
              only:
                - master
                - circle-ci
          requires:
            - build
